
development:
  adapter: postgresql
  encoding: unicode
  database: mp3databasepg_development
  pool: 5
  host: localhost
  username: mp3databasepg
  password: 123

test:
  adapter: postgresql
  encoding: unicode
  database: mp3databasepg_test
  pool: 5
  host: localhost
  username: mp3databasepg
  password: 123

